### ISSUE TITLE
Installation docs omits some dependencies

### ISSUE THREAD

**Issue by druliner** [c2web/uw_boundless#1]
Installation documentation does not list search module, bootstrap theme or jquery_update module as dependencies.

**Comment by jbleys** [comment]
All requirements and instructions are documented in the README file. I believe a theme can't have hard dependencies in the .info file (like modules do) if that's what you're thinking about.

Please note that the "dev" branch is currently the only relevant branch. Ignore the "master" branch for now.

**Comment by druliner** [comment]
Oh. THOSE requirements. I didn't scroll up all the way. Sorry.
