### ISSUE TITLE
Theme assets folder is missing

### ISSUE THREAD

**Issue by sodacrackers** [c2web/uw_boundless#12]
I'm getting 404 errors for the less generated css.  It looks like an `assets` folder should be restored or have references to it dropped.  It's not clear if those assets are needed for the theme.  

E.g. https://github.com/c2web/uw_boundless/blob/5c68f645b7d931b68cafa45116410a84106434c9/less/uw/uw.alert.less#L49

**Comment by jbleys** [comment]
The only less generated css file needed is "style"(all others are imported into that one).
https://github.com/c2web/uw_boundless/blob/5c68f645b7d931b68cafa45116410a84106434c9/less/style.less

The various assets paths refer from style.css to the assets in the assets folder which resides in the css folder.

**Comment by sodacrackers** [comment]
It may make a difference I'm self-compiling Boundless `less` rather than using the precompiled css supplied with the theme. The reason is having the Bootstrap mixins available as well as excellent features that are in Boundless `less` files. 

Drupal's less module, referred to in your `.md`, generates a temp css file from the less but any paths in the css reference the original folder.  Eg 

```
Processing: 
      ./less/styles.css.less 
      .bg { background-image: url( assets/bg.png ); }
Creates: 
      ./sites/default/files/less/styles.111222223333333333.css 
      .bg { background-image: url( /..../sites/all/themes/uw_boundless_sub_theme/less/assets/bg.png ); } 

```

Found a fix with rewrites but alternatively the less and css folders could be merged.  Thnx
