### ISSUE TITLE
UW Boundless requires Bootstrap 7.x-3.0

### ISSUE THREAD

**Issue by ud-meister** [c2web/uw_boundless#13]
The problem is the link in the documentation goes to the project and not the 7.x-3.0 version specifically. The newest version of the bootstrap project is causing this issue.
## REQUIREMENTS
1. UW Boundless requires Bootstrap 7.x-3.0 base-theme. Download Bootstrap 3 for Drupal
   http://ftp.drupal.org/files/projects/bootstrap-7.x-3.0.tar.gz
   http://ftp.drupal.org/files/projects/bootstrap-7.x-3.0.zip
## I found that the updated 7.x-3.1 created javascript issues when trying to execute step three in the configuration documentation.
1. Bootstrap CDN
   The theme uses local bootstrap files (v3.3.1). Make sure that BootstrapCDN is disabled.
   Navigate to Administration > Appearance and click the settings of the UW Boundless theme.
   In the "Bootstrap Settings" section, on the "Advanced" tab:
   Expand "BOOTSTRAPCDN"
   The "BootstrapCDN version" should be disabled.

**Comment by jbleys** [comment]
Thanks Rich, I'll update the requirements with links to the 7.x-3.0 version.
