### ISSUE TITLE
Radios / Checkboxes not appearing

### ISSUE THREAD

**Issue by druliner** [c2web/uw_boundless#2]
See screenshot of modules page with uw_boundless as admin theme. Or enable webform module and add a select field.

I found in css that .checkbox input and .radio input opacity is set to 0.

![uwb-modules-page-checkboxes](https://cloud.githubusercontent.com/assets/4001119/5885404/f401defe-a320-11e4-907c-6eede5dea6a0.png)

**Comment by jbleys** [comment]
In general, the UW Boundless theme has not been thoroughly checked when running in admin mode, and I guess more issues will arise. 

For now I suggest not using it as an admin theme. Instead use one of the core themes, like Seven, and using the administration theme when editing or creating content. 

Collecting the issues around the the use of the theme in admin mode will be helpful, so will keep this open.

In the meantime I'll see if I can make the checkboxes appear. :)

**Comment by jbleys** [comment]
check boxes are visisble.
grab a new copy of style.css, style.css.map and content.less,
