### ISSUE TITLE
Drop Down menus get pushed down page when logged in

### ISSUE THREAD

**Issue by druliner** [c2web/uw_boundless#3]
When logged in, the toolbar at the top of the page pushes the drop down menus down the page making it difficult to get from menu to drop-down tile. (right clicking the upper menu allows you jump across the gap).

![uwb-drop-down-menu-gap](https://cloud.githubusercontent.com/assets/4001119/5885427/823ce3da-a321-11e4-9f41-ab4ca6e23eb0.png)

**Comment by jbleys** [comment]
I'll update the css to fix this.

**Comment by jbleys** [comment]
this is fixed.
grab a new copy of style.css, style.css.map and content.less
