### ISSUE TITLE
Webform email component has squared corners where other elements rounded

### ISSUE THREAD

**Issue by druliner** [c2web/uw_boundless#4]
Create a webform with the email field and to see the corners squared off. 

Note: You can also see the missing checkboxes in this screenshot 
(Under Affiliation next to faculty staff student )

solution to square corners:  add .form-text to form control in style.css

![uwb-webform-email-field-square](https://cloud.githubusercontent.com/assets/4001119/5885467/2efe214c-a322-11e4-8786-c460021916c3.png)

**Comment by jbleys** [comment]
tweaking form elements in general is something I'm still working on.
