### ISSUE TITLE
Docs mention "menu expanded" which is no longer an option

### ISSUE THREAD

**Issue by druliner** [c2web/uw_boundless#5]
The README #8 Main menu links said to click "Show as expanded"

I looked and looked for this option and it appears they've taken it out. (wait, what?)

So I downloaded a module "Menu Expanded" which apparently restores this functionality.
  https://www.drupal.org/project/menu_expanded

We might want to add this module as a dependency for the menu system.

**Comment by jbleys** [comment]
The theme was developed with a clean install of drupal (7.34), and the "Show as expanded" option was available. Unless #8 becomes becomes a persistent issue we should consider mentioning the module as a dependency.  I think for now the line "Some instructions may not apply exactly to existing Drupal 7 installations." suffices.
